default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: recipe_app_development
  username: postgres
  password: Pak1stan

test:
  <<: *default
  database: recipe_app_test
  username: postgres
  password: Pak1stan

production:
  <<: *default
  database: recipe_app_production
  username: recipe_app
  password: <%= ENV["RECIPE_APP_DATABASE_PASSWORD"] %>
